wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/run_flax_speech_recognition_seq2seq_streaming.py
    python_version: 3.8.10
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.28.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681119224.522651
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      - 34
      4: 3.8.10
      5: 0.14.2
      6: 4.28.0.dev0
      8:
      - 5
output_dir:
  desc: null
  value: ../../scream_sep_8tpu_small_6e06_beam5
overwrite_output_dir:
  desc: null
  value: true
do_train:
  desc: null
  value: true
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: IntervalStrategy.NO
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 40
per_device_eval_batch_size:
  desc: null
  value: 8
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 6.0e-06
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 3.0
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: SchedulerType.LINEAR
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 5000
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ../../scream_sep_8tpu_small_6e06_beam5/runs/Apr10_09-32-59_t1v-n-c55670c6-w-0
logging_strategy:
  desc: null
  value: IntervalStrategy.STEPS
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: IntervalStrategy.STEPS
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: null
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
local_rank:
  desc: null
  value: -1
xpu_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 2500
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: Scream - sep_8tpu_small_6e06_beam5
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: true
sharded_ddp:
  desc: null
  value: []
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    fsdp_min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
deepspeed:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: OptimizerNames.ADAMW_HF
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - tensorboard
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: true
resume_from_checkpoint:
  desc: null
  value: 'True'
hub_model_id:
  desc: null
  value: NbAiLab/scream_sep_8tpu_small_6e06_beam5
hub_strategy:
  desc: null
  value: HubStrategy.EVERY_SAVE
hub_token:
  desc: null
  value: null
hub_private_repo:
  desc: null
  value: true
gradient_checkpointing:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: null
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
sortish_sampler:
  desc: null
  value: false
predict_with_generate:
  desc: null
  value: true
generation_max_length:
  desc: null
  value: null
generation_num_beams:
  desc: null
  value: null
generation_config:
  desc: null
  value: null
_n_gpu:
  desc: null
  value: 0
__cached__setup_devices:
  desc: null
  value: cpu
model_name_or_path:
  desc: null
  value: openai/whisper-small
config_name:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
feature_extractor_name:
  desc: null
  value: null
cache_dir:
  desc: null
  value: null
use_fast_tokenizer:
  desc: null
  value: true
model_revision:
  desc: null
  value: main
use_auth_token:
  desc: null
  value: true
dtype:
  desc: null
  value: bfloat16
num_beams:
  desc: null
  value: 5
dataset_name:
  desc: null
  value: NbAiLab/NCC_speech_all_v5
dataset_config_name:
  desc: null
  value: null
text_column:
  desc: null
  value: null
dataset_cache_dir:
  desc: null
  value: null
overwrite_cache:
  desc: null
  value: false
preprocessing_num_workers:
  desc: null
  value: 32
max_train_samples:
  desc: null
  value: null
max_eval_samples:
  desc: null
  value: null
audio_column_name:
  desc: null
  value: audio
text_column_name:
  desc: null
  value: text
max_duration_in_seconds:
  desc: null
  value: 30.0
min_duration_in_seconds:
  desc: null
  value: 0.0
max_label_length:
  desc: null
  value: 128
pad_input_to_multiple_of:
  desc: null
  value: null
pad_target_to_multiple_of:
  desc: null
  value: null
train_split_name:
  desc: null
  value: train
eval_split_name:
  desc: null
  value: validation
do_lower_case:
  desc: null
  value: false
do_remove_punctuation:
  desc: null
  value: false
do_normalize_eval:
  desc: null
  value: true
language:
  desc: null
  value: Norwegian
task:
  desc: null
  value: transcribe
num_train_steps:
  desc: null
  value: 50000
shuffle_buffer_size:
  desc: null
  value: 500
streaming:
  desc: null
  value: true
log_max_eval_predictions:
  desc: null
  value: 100
log_eval_predictions_fn:
  desc: null
  value: log_predictions.write_predictions
run_description:
  desc: null
  value: A Small Scream model. Trained with linear decay only on the all_v5 corpus.
    This version is trained with a learning rate of 6e6.
wandb_entity:
  desc: null
  value: nbailab
wandb_project:
  desc: null
  value: Scream - septimus
