wandb_version: 1

__cached__setup_devices:
  desc: null
  value: cpu
_n_gpu:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    code_path: code/run_flax_speech_recognition_seq2seq_streaming_debug.py
    framework: huggingface
    huggingface_version: 4.28.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1681324924.905429
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      - 34
      4: 3.8.10
      5: 0.14.0
      6: 4.28.0.dev0
      8:
      - 5
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
audio_column_name:
  desc: null
  value: audio
auto_find_batch_size:
  desc: null
  value: false
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
cache_dir:
  desc: null
  value: null
config_name:
  desc: null
  value: null
data_seed:
  desc: null
  value: null
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
dataset_cache_dir:
  desc: null
  value: null
dataset_config_name:
  desc: null
  value: null
dataset_name:
  desc: null
  value: NbAiLab/NCC_speech_all_v5
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_timeout:
  desc: null
  value: 1800
debug:
  desc: null
  value: []
deepspeed:
  desc: null
  value: null
disable_tqdm:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_lower_case:
  desc: null
  value: false
do_normalize_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_remove_punctuation:
  desc: null
  value: false
do_train:
  desc: null
  value: true
dtype:
  desc: null
  value: bfloat16
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
eval_split_name:
  desc: null
  value: validation
eval_steps:
  desc: null
  value: 10000
evaluation_strategy:
  desc: null
  value: IntervalStrategy.NO
feature_extractor_name:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: []
fsdp_config:
  desc: null
  value:
    fsdp_min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
full_determinism:
  desc: null
  value: false
generation_config:
  desc: null
  value: null
generation_max_length:
  desc: null
  value: null
generation_num_beams:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: null
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hub_model_id:
  desc: null
  value: NbAiLab/scream_large_oct_debug_128seq
hub_private_repo:
  desc: null
  value: true
hub_strategy:
  desc: null
  value: HubStrategy.EVERY_SAVE
hub_token:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: true
include_inputs_for_metrics:
  desc: null
  value: false
jit_mode_eval:
  desc: null
  value: false
label_names:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
language:
  desc: null
  value: Norwegian
learning_rate:
  desc: null
  value: 5.0e-06
length_column_name:
  desc: null
  value: length
load_best_model_at_end:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
log_eval_predictions_fn:
  desc: null
  value: log_predictions.write_predictions
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_max_eval_predictions:
  desc: null
  value: 100
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ../../scream_large_oct_debug_128seq/runs/Apr12_18-41-18_t1v-n-0a06f6ef-w-0
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 500
logging_strategy:
  desc: null
  value: IntervalStrategy.STEPS
lr_scheduler_type:
  desc: null
  value: SchedulerType.LINEAR
max_duration_in_seconds:
  desc: null
  value: 30.0
max_eval_samples:
  desc: null
  value: null
max_grad_norm:
  desc: null
  value: 1.0
max_label_length:
  desc: null
  value: 128
max_steps:
  desc: null
  value: -1
max_train_samples:
  desc: null
  value: null
metric_for_best_model:
  desc: null
  value: null
min_duration_in_seconds:
  desc: null
  value: 0.0
model_name_or_path:
  desc: null
  value: openai/whisper-large-v2
model_revision:
  desc: null
  value: main
mp_parameters:
  desc: null
  value: ''
no_cuda:
  desc: null
  value: false
num_beams:
  desc: null
  value: 5
num_train_epochs:
  desc: null
  value: 3.0
num_train_steps:
  desc: null
  value: 50000
optim:
  desc: null
  value: OptimizerNames.ADAMW_HF
optim_args:
  desc: null
  value: null
output_dir:
  desc: null
  value: ../../scream_large_oct_debug_128seq
overwrite_cache:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: true
pad_input_to_multiple_of:
  desc: null
  value: null
pad_target_to_multiple_of:
  desc: null
  value: null
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 5
per_device_train_batch_size:
  desc: null
  value: 3
per_gpu_eval_batch_size:
  desc: null
  value: null
per_gpu_train_batch_size:
  desc: null
  value: null
predict_with_generate:
  desc: null
  value: true
prediction_loss_only:
  desc: null
  value: false
preprocessing_num_workers:
  desc: null
  value: 32
push_to_hub:
  desc: null
  value: true
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
remove_unused_columns:
  desc: null
  value: true
report_to:
  desc: null
  value:
  - tensorboard
  - wandb
resume_from_checkpoint:
  desc: null
  value: 'True'
run_description:
  desc: null
  value: A Large Whisper Scream model with 5 batch size. Trained with 5e-6 and linear
    decay on the all_v5-corpus.
run_name:
  desc: null
  value: ScreamLarge - debug_beam5_long
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 500
save_strategy:
  desc: null
  value: IntervalStrategy.STEPS
save_total_limit:
  desc: null
  value: null
seed:
  desc: null
  value: 42
sharded_ddp:
  desc: null
  value: []
shuffle_buffer_size:
  desc: null
  value: 500
skip_memory_metrics:
  desc: null
  value: true
sortish_sampler:
  desc: null
  value: false
streaming:
  desc: null
  value: true
task:
  desc: null
  value: transcribe
text_column:
  desc: null
  value: null
text_column_name:
  desc: null
  value: text
tf32:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
torchdynamo:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
train_split_name:
  desc: null
  value: train
use_auth_token:
  desc: null
  value: true
use_fast_tokenizer:
  desc: null
  value: true
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: nbailab
wandb_project:
  desc: null
  value: Scream - septimus
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 10000
weight_decay:
  desc: null
  value: 0.0
xpu_backend:
  desc: null
  value: null
